### ISSUE TITLE
crash happened in PebbleDictionary class

### ISSUE THREAD

**Issue by Kevin-Misfit** [pebble/pebble-android-sdk#6]
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'int com.getpebble.android.kit.util.PebbleTuple$TupleType.ordinal()' on a null object reference
       at com.getpebble.android.kit.util.PebbleDictionary.fromJson(PebbleDictionary.java:320)
       at com.getpebble.android.kit.PebbleKit$PebbleDataReceiver.onReceive(PebbleKit.java:552)
       at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:885)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:224)
       at android.app.ActivityThread.main(ActivityThread.java:5526)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by sjp4** [comment]
@Kevin-Misfit Thanks for the report. Are you using PebbleKit v3.1.0, which was released last week? This issue should be fixed in that version

**Comment by Kevin-Misfit** [comment]
Ok, may i ask why the crash happened? i just wanna make sure, this is not a problem that caused from our side.

**Comment by sjp4** [comment]
The crash was seen in some `Locale`s (e.g. Turkish) due to a fault in processing inbound messages from the watch, because of Locale-specific String processing inside the PebbleKit library
